### ISSUE TITLE
Can't complete the conversion, in gpu will flash back in the last 2%

### ISSUE THREAD

**Issue by Wszhdg** [jianchang512/stt#10]
I installed the driver correctly and I can also use cuda, and the problem occurs in cuda, cpu doesn't have this problem for now, and the problem has nothing to do with the model version, neither the base model nor the biggest l3 can complete the conversion it will flash back at the end, I'm using cuda12.3

**Comment by jianchang512** [comment]
Temporarily pull the source code for deployment

**Comment by jianchang512** [comment]
update to 0.0.7
