### ISSUE TITLE
Plus? 

### ISSUE THREAD

**Issue by opoczki** [jianchang512/stt#16]
Hi! 
I have downloaded a whisper model file which contains multilanguages, so it recognizes languages like mine, which is Hungarian. It is not listed in the drop down list. In the "page source" section I see this image, I just can't add an extra language by editing. So this: <option value="hu">Hungarian</option>.

When I try to edit the layui.js file, I see chaos and when I search for text, it doesn't return any results if I type in, say, French. 
Same with layui.css file. 
Please help me how I can add my language. Thank you.

**Comment by opoczki** [comment]
![IMG_20240206_140132](https://github.com/jianchang512/stt/assets/140985031/86e2262f-3239-43df-8e5f-d63911866b9a)

**Comment by jianchang512** [comment]
git pull ,has add hu
