### ISSUE TITLE
提示WhisperModel.__init__() got an unexpected keyword argument 'download_root'

### ISSUE THREAD

**Issue by hxyiya** [jianchang512/stt#2]
![微信图片_20240111145115](https://github.com/jianchang512/stt/assets/102878613/55efc829-5e04-4577-a995-8e5ab8d96ae3)

**Comment by jianchang512** [comment]
源码版？预编译版？
完整错误截图

**Comment by hxyiya** [comment]
源码版，只有网页里有点击识别后有这个提示，控制台没有提示

**Comment by jianchang512** [comment]
用的是faster-whisper，确定依赖正确

然后start.py里输出调试吧。正常不应该有这个错误

**Comment by hxyiya** [comment]
感谢回复，已解决
