### ISSUE TITLE
在语音识别完成后闪退

### ISSUE THREAD

**Issue by 1468478951** [jianchang512/stt#23]
我在采用预先分割和均等分割时，在语音识别完成后，应该即将进入翻译阶段时都会出现闪退。在日志最后显示“INFO:VideoTrans:语音识别完成 / 266
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found application patches to be applied.”似乎没有明显问题，我也不明白是什么情况。

**Comment by 1468478951** [comment]
我可能发错地方了

**Comment by 1468478951** [comment]
我使用large模型会报错cuda显存不足，我的专用显存为6G，我使用的是medium。我不太认为是模型问题，因为日志中每次都是在出现“INFO:VideoTrans:语音识别完成 / 123”后就闪退了，即便我按照你所说的将best_of和beam_size都为1也同样如此。按照我的理解，代码会先将视频中音频提出，然后输入模型得到字幕，再进行翻译。因此我猜测因为模型导致的显存问题闪退一般应该发生在音频转文字的推理过程中，但我总是在全部识别完成后发生闪退。当然我并不清楚具体的构建情况，这只是基于我所进行相关工作的一个推理。同时这种情况仅发生在预先分割和均等分割时，整体识别不会有问题但效果不好。不知道我提供的信息能否使你发现问题，或者得到解决方法。

**Comment by jianchang512** [comment]
faster-whisper模型一直存在该问题，可以再试试将 set.ini 中的 `condition_on_previous_text=true` 改为 `condition_on_previous_text=false`
