### ISSUE TITLE
预编译版，api上传失败报错：ERROR in start: [api]error: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by DYminecraft** [jianchang512/stt#3]
打扰了。
预编译版，网页端处理同一段音频没问题，但python调用api报错“上传失败”。
小白诚心提问，该如何处理呢？
![1](https://github.com/jianchang512/stt/assets/62377256/938292ee-137c-4539-8a7d-1845b696bee1)

**Comment by jianchang512** [comment]
有点bug  晚上可更新或者使用源码版部署

**Comment by jianchang512** [comment]
fixed at v0.0.4

**Comment by chenxinss** [comment]
作者修复速度好快。我也遇到这个问题了。
怀疑是我本地问题，然后先使用源码部署看看啥问题了，刚跑起来这就修复了，回头再试试

**Comment by xunaolong** [comment]
![image](https://github.com/jianchang512/stt/assets/155403647/04d51b3f-8028-435f-bbd7-7b888d30a242)
![image](https://github.com/jianchang512/stt/assets/155403647/64b03910-b4df-4259-a81d-fbb1153f87b0)
想请问一下，我上传音频文件成功了但是却无法识别是什么情况，我使用的是预编译的方法

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/stt/assets/3378335/2d8f483d-99a6-4eea-ae0d-cc70d0a328e2)

https://github.com/jianchang512/stt?tab=readme-ov-file#%E6%B3%A8%E6%84%8F

**Comment by xunaolong** [comment]
> ![image](https://private-user-images.githubusercontent.com/3378335/297254555-2d8f483d-99a6-4eea-ae0d-cc70d0a328e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDI3MDMsIm5iZiI6MTcwNTU0MjQwMywicGF0aCI6Ii8zMzc4MzM1LzI5NzI1NDU1NS0yZDhmNDgzZC05OWE2LTRlZWEtYWUwZC1jYzcwZDBhMzI4ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDE0NjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFjNTA3Y2E3ZmU5NzMzMWFkYmNmOGU1OTcxMjY0ZDM0ZDRjNjE0NzM3MGViYWZhY2I5OTcxN2VhZDQ2YTlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NTVZrEtQZ8Oxovcwnjz-VCXw0DhfpTm4ccC9i45rA6Q)
> 
> https://github.com/jianchang512/stt?tab=readme-ov-file#%E6%B3%A8%E6%84%8F

已解决，谢谢！
