### ISSUE TITLE
ERROR: No matching distribution found for torch==2.1.2+cu121

### ISSUE THREAD

**Issue by super5hunz1** [jianchang512/stt#4]
![image](https://github.com/jianchang512/stt/assets/29603143/14dc3477-9804-4649-9ce3-e8682ea01a1c)

**Comment by jianchang512** [comment]
打开 requirements.txt  删掉 torch后的  +cu121
然后再次执行安装

**Comment by super5hunz1** [comment]
> 打开 requirements.txt 删掉 torch后的 +cu121 然后再次执行安装

![image](https://github.com/jianchang512/stt/assets/29603143/49ece8cb-ef51-4acc-a70c-03b5365c3d68)

这样是可以成功安装了，cuda没生效，

pip uninstall torch torchvision torchaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
再这样就可以了

**Comment by jianchang512** [comment]
fixed
