### ISSUE TITLE
遇到终端显示cublasxx.dll不存在”的错误，但是cuBLAS下载不了

### ISSUE THREAD

**Issue by lotusflovver** [jianchang512/stt#50]
cuBLAS的下载链接点进去是404，英伟达官网也没有windows的版本可以用。请问应该到哪里下载呢？

**Comment by jianchang512** [comment]
任意文件夹地址栏输入cmd打开黑窗口，输入命令nvcc -V查看当前CUDA版本

CUDA11.x版本点击此处下载 https://github.com/jianchang512/stt/releases/download/0.0/cuBLAS.and.cuDNN_CUDA11_win_v4.7z

CUDA12.x版本点击此处下载 https://github.com/jianchang512/stt/releases/download/0.0/cuBLAS.and.cuDNN_CUDA12_win_v1.7z

**Comment by lotusflovver** [comment]
问题解决了，感谢
