### ISSUE TITLE
有点过份的需求

### ISSUE THREAD

**Issue by arke56** [jianchang512/stt#57]
1. 翻译的文字，可以自定义加载文字字体以及设置位置就完美了
2. 可以只保留背景，把视频中的原声去掉更完美了，很多时候，只需要背景音然后加一点描述文字就可以了

虽然是免费的，但是做为这么好用的工具，不提一点需求，就有点不过份了

**Comment by jianchang512** [comment]
https://github.com/jianchang512/pyvideotrans

使用这个 支持

**Comment by arke56** [comment]
> https://github.com/jianchang512/pyvideotrans
> 
> 使用这个 支持

没太懂，我不就是用的这个吗？

**Comment by jianchang512** [comment]
你在stt仓库发的


字幕调整
https://pyvideotrans.com/fontset.html

**Comment by arke56** [comment]
> 你在stt仓库发的
> 
> 字幕调整 https://pyvideotrans.com/fontset.html

我懂了，可以直接在videotrans/set.ini里面设置视频字体样式和位置，谢谢
