### ISSUE TITLE
api局域网没法使用呢

### ISSUE THREAD

**Issue by cqjunge** [jianchang512/stt#62]
1.api局域网没法使用呢，
2.另外用linux运行，始终提示模板没有，但是Windows模板能运行，

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/stt/assets/3378335/c6d58b1a-edc1-4dd1-a490-47ec6e3efdf5)

set.ini中修改ip为ju'y局域网ip

**Comment by cqjunge** [comment]
网页版是局域网的支持的，但是api只能127.0.0.1这个地址

**Comment by jianchang512** [comment]
set.ini中自行修改地址即可。
