### ISSUE TITLE
上传失败，网页可正常打开，求教如何解决

### ISSUE THREAD

**Issue by wthualala** [jianchang512/stt#66]
![chrome_1z6vZyQGpT](https://github.com/user-attachments/assets/e7513c7c-bd68-44f0-894d-1b8cd9291d95)

**Comment by wthualala** [comment]
![Uploading WindowsTerminal_oRj8SQ0GdY.png…]()

**Comment by wthualala** [comment]
![WindowsTerminal_oRj8SQ0GdY](https://github.com/user-attachments/assets/beb93f1c-2d3d-45ca-b318-590ee9b46ebc)

**Comment by jianchang512** [comment]
更新到 0.93

**Comment by wthualala** [comment]
谢谢帮助，已解决。可能是缺失ffmpeg的原因。
ffmpeg.exe下载
如果你的计算机上没有ffmpeg，请下载这2个exe文件，和 start.exe放在同一位置
