### ISSUE TITLE
打开网页，上传后文件都没有内容

### ISSUE THREAD

**Issue by zhouyuyu888** [jianchang512/stt#72]
点播放的三角什么都听不到，
主控没有报错
E:\BaiduNetdiskDownload\win-stt-0.0.93>.\start.exe
{'web_address': '127.0.0.1:9977', 'lang': 'zh', 'devtype': 'cpu', 'cuda_com_type': 'int8', 'beam_size': 1, 'best_of': 1, 'vad': True, 'temperature': 0, 'condition_on_previous_text': False, 'initial_prompt_zh': '以下是普通话内容，请转录为中 文简体。'}

如果设备使用英伟达显卡并且CUDA环境已正确安装，可修改set.ini中
devtype=cpu 为 devtype=cuda, 然后重新启动以加快识别速度

浏览器已打开，若未能自动打开，请手动打开网址  http://127.0.0.1:9977

**Comment by jianchang512** [comment]
ffmpeg.exe下载
如果你的计算机上没有ffmpeg，请下载这2个exe文件，和 start.exe放在同一位置

https://github.com/jianchang512/stt/releases/download/v0.93/ffmpeg.exe

https://github.com/jianchang512/stt/releases/download/v0.93/ffprobe.exe

**Comment by zhouyuyu888** [comment]
谢谢答复，我把这两个文件放到start.exe目录了，但传上去的文件还是0长度。

**Comment by zhouyuyu888** [comment]
上传的文件mp3格式是4M，wav格式是49M，两个格式本地都能播放， 上传上去的文件显示是0大小，点下载下载的文件只有14K，感觉还没到识别的地方，上传就出错了。

**Comment by zhouyuyu888** [comment]
原因找到了，原来是因为手机录音是.m4a文件，第一次上传系统不认，用转换工具转换后重新上传，因为文件名除扩展名外前面都一样，系统还记着第一次不认的文件，所以上度一直是0，改成其他名字后再上传就好了。
