### ISSUE TITLE
how can use my GPUS?

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/stt#8]
i want to know in windows 64bit use not CPU, GPU instead, becuase with CPU is a lot of time:

![SNAG-0229](https://github.com/jianchang512/stt/assets/428820/fdfb629c-4e60-424d-9317-31b39747c1c5)

Consider put a progress bar pls

**Comment by jianchang512** [comment]
By default, CPU operation is used. If you are sure to use a NVIDIA graphics card and have configured the CUDA environment, please modify the `devtype=cpu` in `set.ini`  to `devtype=cuda` and restart to use CUDA acceleration

**Comment by johnfelipe** [comment]
https://drive.google.com/file/d/1QF7m_i6_iucxmqkEqkfZhr4K0ysOY2ER/view?usp=sharing

is taking a lot of time, a video with 14 min transcribe in 3 min with faster v3, with my GPU, pls review video and tell me what i need to do for use your webapp

**Comment by jianchang512** [comment]
Sometimes you will encounter an error "cublasxx.dll does not exist", at this time you need to download cuBLAS, and then copy the dll file to the system directory, [click to download cuBLAS](https://github.com/jianchang512/stt/releases/download/0.0/cuBLAS_win.7z), after decompression, copy the dll file inside to C:/Windows/System32

**Comment by jianchang512** [comment]
update v0.0.6

**Comment by johnfelipe** [comment]
![SNAG-0257](https://github.com/jianchang512/stt/assets/428820/299ef00a-3c51-438e-90a6-ac56832938fc)

dont finish....

**Comment by jianchang512** [comment]
no error at console cmd or web console panel?

**Comment by johnfelipe** [comment]
nop, only stack in 98%, how can debug for u?

**Comment by jianchang512** [comment]
app.log or start.log file,and F12 view web console panel

**Comment by johnfelipe** [comment]
![SNAG-0266](https://github.com/jianchang512/stt/assets/428820/ad03939f-4d08-4382-b631-6f0679fbf315)

just close exe window and dont finish it

**Comment by jianchang512** [comment]
update to 0.0.7
