### ISSUE TITLE
whisper-large-v3-turbo

### ISSUE THREAD

**Issue by libin11li** [jianchang512/stt#88]
你好，请问支持whisper-large-v3-turbo模型吗

**Comment by jianchang512** [comment]
目前faster-whisper官方还不支持，如果源码部署，可以通过修改源码文件实现

在此下载faster-whisper下的 large-v3-turbo模型 https://github.com/jianchang512/stt/releases/tag/0.0

源码部署需修改虚拟环境/lib/site-packages/faster_whisper/utils.py 文件第23行增加一行代码

"large-v3-turbo": "Systran/faster-whisper-large-v3-turbo",

**Comment by libin11li** [comment]
ok
