### ISSUE TITLE
put download button / now not stock in 98% - pls view video

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/stt#9]
https://drive.google.com/file/d/1Vn28cht--INSiRlKrJzWYlDvLOM8jOkf/view?usp=drivesdk

may be will amazing if we have a download button:
download srt
download TXT
download json

**Comment by jianchang512** [comment]
Temporarily pull the source code for deployment

**Comment by johnfelipe** [comment]
When you release new version with download buttons?
