### ISSUE TITLE
add hebrew

### ISSUE THREAD

**Issue by GreenAA** [jianchang512/stt#95]
Hi jian 

you app pyvideotrans is perfect ,, i love it . 

if you can add heb to all app is be perfect , 

thanks

**Comment by jianchang512** [comment]
update to 0.0.98 and use  Automatic Detection

**Comment by GreenAA** [comment]
Thanks

You the best 👌

בתאריך יום ד׳, 20 בנוב׳ 2024, 09:40, מאת okmyworld ‏<
***@***.***>:
